# Generated by Django 4.1.3 on 2023-09-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_card_options_card_sort_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarot',
            old_name='card',
            new_name='rank',
        ),
        migrations.AlterField(
            model_name='tarot',
            name='image',
            field=models.FilePathField(null=True, path='C:\\Users\\ryaanahmed\\dev\\french-playing-cards\\assets\\img\\cartomancy'),
        ),
    ]
