# Generated by Django 3.1.5 on 2021-11-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211105_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='back_notes',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='db_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='maker',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='suit',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='town',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='period',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='recto_or_verso',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
