# Generated by Django 3.1.5 on 2021-11-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211116_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='end_date',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='start_date',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
