# Generated by Django 3.1.5 on 2021-11-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211116_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='end_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='start_date',
            field=models.IntegerField(null=True),
        ),
    ]
