# Generated by Django 3.1.5 on 2021-12-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211129_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.FilePathField(null=True, path='app/images/'),
        ),
    ]
