# Generated by Django 3.1.5 on 2021-12-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.FilePathField(default='could not find matching title', match='JC1.jpeg', path='app/images/'),
        ),
    ]
