# Generated by Django 3.1.5 on 2021-12-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211229_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.FilePathField(null=True, path='app/images/'),
        ),
    ]
