# Generated by Django 4.1.3 on 2023-04-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211229_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=2)),
                ('number', models.IntegerField()),
                ('orientation', models.BooleanField(blank=True)),
                ('card', models.CharField(max_length=1)),
                ('title', models.CharField(blank=True, max_length=30)),
                ('subtitle', models.CharField(blank=True, max_length=30)),
                ('pair', models.CharField(blank=True, max_length=20)),
                ('etteilla', models.CharField(blank=True, max_length=25)),
                ('quad', models.CharField(blank=True, max_length=20)),
                ('triple', models.CharField(blank=True, max_length=20)),
                ('double', models.CharField(blank=True, max_length=20)),
                ('image', models.FilePathField(null=True, path='assets/img/divination/')),
            ],
        ),
    ]
