# Generated by Django 4.1.3 on 2023-04-25 17:01

from django.db import migrations
import csv

def populate_tarot(apps, schema_editor):
    Tarot = apps.get_model("app", "Tarot")

    tarot_cards = []

    with open("app/data/tarot/tarot_english.csv", newline='') as csvfile:
        tarot_cards = list(csv.DictReader(csvfile))
    
    for card in tarot_cards:
        image_string = card["number"] + card["orientation"] + ".jpeg"

        card = {k: v for k, v in card.items() if v}
        card["number"] = int(card["number"])
        if "orientation" in card:
            card["orientation"] = bool(int(card["orientation"]))


        tarot_model = Tarot(lang="en", image=image_string, **card)
        tarot_model.save()

    tarot_cards = []

    with open("app/data/tarot/tarot_francais.csv", newline='') as csvfile:
        tarot_cards = list(csv.DictReader(csvfile))
    
    for card in tarot_cards:
        image_string = card["number"] + card["orientation"] + ".jpeg"

        card = {k: v for k, v in card.items() if v}
        card["number"] = int(card["number"])
        if "orientation" in card:
            card["orientation"] = bool(int(card["orientation"]))


        tarot_model = Tarot(lang="fr", image=image_string, **card)
        tarot_model.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_tarot_orientation'),
    ]

    operations = [
        migrations.RunPython(populate_tarot)
    ]
